import { getBranchOpeningAssessment, startBranchProjectV7 } from "../../game/engine";
import type { BranchProfile, GameState } from "../../game/store";
import type { GameAction } from "../common";
import { money } from "../format";

const profiles: BranchProfile[] = ["retail", "mortgage", "business", "wealth"];

export function ExpansionModalV9({ game, selectedDistrictId, setSelectedDistrictId, profile, setProfile, action, onClose }: { game: GameState; selectedDistrictId: string; setSelectedDistrictId: (id: string) => void; profile: BranchProfile; setProfile: (profile: BranchProfile) => void; action: GameAction; onClose: () => void }) {
  const district = game.districts.find((item) => item.id === selectedDistrictId) ?? game.districts[0];
  const assessment = district ? getBranchOpeningAssessment(game, district.id) : null;
  return <div className="v9-modal-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="v9-expansion-modal panel"><header><div><p className="eyebrow">EXPANSION MAP</p><h2>Choose the next market</h2><p>The network table stays compact; market selection opens only when you are expanding.</p></div><button onClick={onClose}>×</button></header><div className="v9-expansion-layout"><div className="v9-district-list">{game.districts.map((item) => <button key={item.id} className={district?.id === item.id ? "selected" : ""} onClick={() => setSelectedDistrictId(item.id)}><strong>{item.name}</strong><small>{item.description}</small><span>Population {item.population.toLocaleString("en-GB")} · Competition {item.competition}</span></button>)}</div>{district && <aside><h3>{district.name}</h3><p>{district.description}</p><div className="v9-market-metrics"><MetricV9 label="Opening cost" value={money.format(district.openingCost)} /><MetricV9 label="Monthly rent" value={money.format(district.monthlyRent)} /><MetricV9 label="Retail demand" value={`${district.retailDemand}`} /><MetricV9 label="Business demand" value={`${district.businessDemand}`} /></div><label><span>Branch profile</span><select value={profile} onChange={(event) => setProfile(event.target.value as BranchProfile)}>{profiles.map((item) => <option key={item} value={item}>{item}</option>)}</select></label>{assessment && assessment.reasons.length > 0 && <div className="v9-blockers">{assessment.reasons.map((reason) => <span key={reason}>{reason}</span>)}</div>}<div className="v9-modal-actions"><button className="secondary" disabled={!assessment?.financeAllowed} onClick={() => { action((state) => startBranchProjectV7(state, district.id, profile, "financed")); onClose(); }}>Finance opening</button><button className="primary" disabled={!assessment?.cashAllowed} onClick={() => { action((state) => startBranchProjectV7(state, district.id, profile, "cash")); onClose(); }}>Fund with cash</button></div></aside>}</div></section></div>;
}

export function LedgerColumnV9({ title, total, rows }: { title: string; total: number; rows: Array<[string, number]> }) { return <div className="v9-ledger-column"><header><strong>{title}</strong><b>{money.format(total)}</b></header>{rows.map(([label, value]) => <div key={label}><span>{label}</span><strong>{money.format(value)}</strong></div>)}</div>; }
export function ForecastV9({ days, value }: { days: string; value: number }) { return <div><small>{days} DAYS</small><strong className={value >= 0 ? "positive" : "negative"}>{money.format(value)}</strong></div>; }
export function MetricV9({ label, value, detail, tone }: { label: string; value: string; detail?: string; tone?: string }) { return <article className={`v9-metric ${tone ?? ""}`}><small>{label}</small><strong>{value}</strong>{detail && <span>{detail}</span>}</article>; }
