import { applyForPromotion, takeCourse, takeDividend } from "../../game/engine";
import type { GameState } from "../../game/store";
import type { GameAction } from "../common";
import { money } from "../format";

const careerTitles = ["Local Founder", "Banking Executive", "Regional Director", "Group CEO", "Industry Leader"];
const educationTitles = ["Self-taught", "Banking Certificate", "Finance Diploma", "Executive Banking Programme", "Advanced Leadership"];

export function CareerPage({ game, action }: { game: GameState; action: GameAction }) {
  return <section className="content-grid two-column"><article className="panel profile-card"><div className="large-avatar">{game.founderName.slice(0, 1).toUpperCase()}</div><p className="eyebrow">FOUNDER PROFILE</p><h2>{game.founderName}</h2><p>{careerTitles[game.careerLevel]} · {game.background} background</p><div className="profile-stats"><span><small>Personal cash</small><strong>{money.format(game.personalCash)}</strong></span><span><small>Skill points</small><strong>{game.skillPoints}</strong></span><span><small>Achievements</small><strong>{game.achievements.length}</strong></span><span><small>Board confidence</small><strong>{game.boardConfidence.toFixed(0)}</strong></span></div><button className="secondary wide" disabled={game.cash < 1_200_000 || game.boardConfidence < 35} onClick={() => action(takeDividend)}>Take founder dividend · NOK 100k</button></article><article className="panel"><div className="panel-heading"><div><p className="eyebrow">CAREER & EDUCATION</p><h3>{educationTitles[Math.min(game.educationLevel, educationTitles.length - 1)]}</h3></div></div><div className="career-step"><span>01</span><div><strong>Executive banking course</strong><p>Costs NOK 30,000 personally and grants two skill points.</p></div><button className="primary small" disabled={game.personalCash < 30_000 || game.educationLevel >= 4} onClick={() => action(takeCourse)}>Enrol</button></div><div className="career-step"><span>02</span><div><strong>Founder career milestone</strong><p>Spend two skill points to increase status and personal earnings.</p></div><button className="primary small" disabled={game.skillPoints < 2 || game.careerLevel >= 4} onClick={() => action(applyForPromotion)}>Advance</button></div><div className="achievement-list"><p className="eyebrow">ACHIEVEMENTS</p>{game.achievements.length === 0 ? <small>No milestones unlocked yet.</small> : game.achievements.map((item) => <span key={item}>◆ {item.replaceAll("-", " ")}</span>)}</div></article></section>;
}
