import { approveLoan, rejectLoan } from "../../game/engine";
import type { GameState } from "../../game/store";
import { Progress, type GameAction } from "../common";
import { cn, money } from "../format";

export function CreditPage({ game, action }: { game: GameState; action: GameAction }) {
  return <>
    <section className="metrics-grid credit-metrics"><article className="metric-card"><div className="metric-label">Non-performing loans</div><div className="metric-value">{game.nplRatio.toFixed(2)}%</div><Progress value={game.nplRatio * 8} warning={game.nplRatio > 4} /></article><article className="metric-card"><div className="metric-label">Loan-loss reserve</div><div className="metric-value">{money.format(game.loanLossReserve)}</div><div className="metric-change">Covers {((game.loanLossReserve / Math.max(1, game.loans)) * 100).toFixed(2)}% of loans</div></article><article className="metric-card"><div className="metric-label">Credit losses today</div><div className="metric-value">{money.format(game.creditLosses)}</div><div className={cn("metric-change", game.creditLosses > 5000 ? "warn" : "good")}>Economic cycle: {game.economicCycle}</div></article><article className="metric-card"><div className="metric-label">Applications waiting</div><div className="metric-value">{game.loanApplications.length}</div><div className="metric-change">New applications arrive every five days</div></article></section>
    <section className="panel"><div className="panel-heading"><div><p className="eyebrow">CREDIT COMMITTEE</p><h3>Large loan applications</h3></div></div>{game.loanApplications.length === 0 ? <div className="empty-state"><strong>No applications waiting</strong><p>Advance time to receive larger cases for manual approval.</p></div> : <div className="loan-list">{game.loanApplications.map((loan) => <article className="loan-row" key={loan.id}><span className={cn("risk-grade", `grade-${loan.riskGrade.toLowerCase()}`)}>{loan.riskGrade}</span><div><strong>{loan.customerName}</strong><small>{loan.segment} · {loan.collateral}% collateral</small></div><span><small>Amount</small><b>{money.format(loan.amount)}</b></span><span><small>Rate</small><b>{loan.rate.toFixed(2)}%</b></span><span><small>Default risk</small><b>{loan.defaultChance.toFixed(1)}%</b></span><div className="loan-actions"><button className="secondary" onClick={() => action((state) => rejectLoan(state, loan.id))}>Decline</button><button className="primary" disabled={game.cash < loan.amount} onClick={() => action((state) => approveLoan(state, loan.id))}>Approve</button></div></article>)}</div>}</section>
  </>;
}
