import { runMarketingCampaign, upgradeDigitalBank } from "../../game/engine";
import type { GameState } from "../../game/store";
import { Progress, type GameAction } from "../common";

export function CustomersPage({ game, action }: { game: GameState; action: GameAction }) {
  return <section className="content-grid two-column">
    <article className="panel"><div className="panel-heading"><div><p className="eyebrow">CUSTOMER BASE</p><h3>{game.customers.toLocaleString("en-GB")} active customers</h3></div></div><div className="segment"><div><strong>Everyday banking</strong><small>{Math.round(game.customers * .52)} customers</small></div><Progress value={52} /></div><div className="segment"><div><strong>Savers</strong><small>{Math.round(game.customers * .27)} customers</small></div><Progress value={27} /></div><div className="segment"><div><strong>Borrowers & business</strong><small>{Math.round(game.customers * .21)} customers</small></div><Progress value={21} /></div><div className="customer-health"><span><small>Satisfaction</small><strong>{game.satisfaction.toFixed(0)}/100</strong></span><span><small>Brand strength</small><strong>{game.brandStrength.toFixed(0)}/100</strong></span><span><small>Today</small><strong>+{game.customersGained} / -{game.customersLost}</strong></span></div></article>
    <div className="stacked-panels"><article className="panel campaign-card"><div className="campaign-graphic"><span>◎</span></div><p className="eyebrow">GROWTH CAMPAIGN</p><h2>Win the local market.</h2><p>Target households near your branches. Results depend on reputation, product range and the economy.</p><button className="primary" disabled={game.cash < 180_000} onClick={() => action(runMarketingCampaign)}>Launch campaign · NOK 180k</button></article><article className="panel"><p className="eyebrow">DIGITAL EXPERIENCE</p><h3>Digital level {game.digitalLevel.toFixed(0)}/100</h3><Progress value={game.digitalLevel} warning={game.digitalLevel < 35} /><p className="muted">A stronger app improves acquisition and reduces service pressure.</p><button className="secondary wide" disabled={game.cash < 650_000 || game.digitalLevel >= 100} onClick={() => action(upgradeDigitalBank)}>Upgrade platform · NOK 650k</button></article></div>
  </section>;
}
