import type { GameState } from "../../game/store";
import type { Competitor } from "../../game/types";
import { CompetitorRow, Progress } from "../common";
import { cn } from "../format";

export function MarketPage({ game }: { game: GameState }) {
  const player = { id: "player", name: game.bankName, strategy: "player" as const, customers: game.customers, deposits: game.deposits, loans: game.loans, reputation: game.reputation, marketShare: game.marketShare, depositRate: game.depositRate, loanRate: game.loanRate, branches: game.branches, digitalLevel: game.digitalLevel, acquisitionPrice: 0 };
  const ranked = [player, ...game.competitors].sort((a, b) => b.marketShare - a.marketShare);
  const recentMoves = game.competitorMoves.filter((move) => move.day >= game.day - 120).slice(0, 8);
  const recentExits = game.competitorHistory.filter((entry) => entry.day >= game.day - 365).slice(0, 5);
  const bestDepositRate = game.competitors.length ? Math.max(...game.competitors.map((item) => item.depositRate)) : game.depositRate;
  const lowestLoanRate = game.competitors.length ? Math.min(...game.competitors.map((item) => item.loanRate)) : game.loanRate;
  const displayedShare = ranked.reduce((sum, item) => sum + item.marketShare, 0);
  return <>
    <section className={cn("economy-hero", `cycle-${game.economicCycle}`)}><div><p className="eyebrow light">MACRO ECONOMY</p><h2>{game.economicCycle[0].toUpperCase() + game.economicCycle.slice(1)}</h2><p>Economic conditions change every month and affect demand, credit losses and customer confidence.</p></div><div className="economy-stats"><span><small>Policy rate</small><strong>{game.baseRate.toFixed(2)}%</strong></span><span><small>Inflation</small><strong>{game.inflation.toFixed(1)}%</strong></span><span><small>GDP growth</small><strong>{game.gdpGrowth.toFixed(1)}%</strong></span><span><small>Unemployment</small><strong>{game.unemployment.toFixed(1)}%</strong></span><span><small>Confidence</small><strong>{game.consumerConfidence.toFixed(0)}</strong></span></div></section>

    <section className="market-operations-layout">
      <article className="panel market-table"><div className="panel-heading"><div><p className="eyebrow">COMPETITIVE LANDSCAPE</p><h3>{game.competitors.length} active rivals · {displayedShare.toFixed(1)}% represented</h3><p>Every active bank is ranked. Acquired and withdrawn banks move to market history.</p></div></div>{ranked.map((item, index) => item.id === "player" ? <div className="competitor-row player-row" key={item.id}><span className="rank-number">{index + 1}</span><div className="competitor-logo">{game.bankName.slice(0, 1)}</div><div><strong>{game.bankName}</strong><small>Your bank · {game.customers.toLocaleString("en-GB")} customers</small></div><span><small>Market share</small><b>{game.marketShare.toFixed(2)}%</b></span><span><small>Reputation</small><b>{game.reputation.toFixed(0)}</b></span></div> : <CompetitorRow key={item.id} competitor={item as Competitor} rank={index + 1} />)}</article>

      <aside className="panel competitor-move-panel"><div className="panel-heading"><div><p className="eyebrow">COMPETITOR INTELLIGENCE</p><h3>Last 120 days</h3></div><span className="status good">Monthly cycle</span></div>{recentMoves.length === 0 ? <div className="empty-state"><strong>No recent competitor move.</strong><p>Advance to the next monthly close. Rivals vary pricing, products, service, digital investment, branches and talent.</p></div> : <div className="competitor-move-list">{recentMoves.map((move) => <article key={move.id}><span>{move.type.slice(0, 2).toUpperCase()}</span><div><small>DAY {move.day} · {game.day - move.day === 0 ? "TODAY" : `${game.day - move.day} DAYS AGO`} · {move.competitorName}</small><strong>{move.title}</strong><p>{move.description}</p></div><b>Impact {move.impact}</b></article>)}</div>}{recentExits.length > 0 && <div className="v813-market-history"><small>MARKET HISTORY · LAST YEAR</small>{recentExits.map((entry) => <span key={`${entry.id}-${entry.day}`}><strong>{entry.name}</strong><b>{entry.reason === "acquired" ? `Acquired by ${entry.buyer ?? "another bank"}` : entry.reason === "merged" ? "Merged" : "Withdrew"} · day {entry.day}</b></span>)}</div>}</aside>
    </section>

    <section className="content-grid two-column"><article className="panel"><p className="eyebrow">CUSTOMER CONFIDENCE</p><h3>{game.consumerConfidence.toFixed(0)}/100</h3><Progress value={game.consumerConfidence} warning={game.consumerConfidence < 45} /><p className="muted">Higher confidence supports borrowing and lower default rates.</p></article><article className="panel"><p className="eyebrow">PRICING POSITION</p><div className="score-list"><span><small>Your savings rate</small><strong>{game.depositRate.toFixed(2)}%</strong></span><span><small>Best competitor</small><strong>{bestDepositRate.toFixed(2)}%</strong></span><span><small>Your loan rate</small><strong>{game.loanRate.toFixed(2)}%</strong></span><span><small>Lowest competitor</small><strong>{lowestLoanRate.toFixed(2)}%</strong></span></div></article></section>
  </>;
}
