import { hireEmployee, improveCyberSecurity, openBranch, upgradeDigitalBank } from "../../game/engine";
import type { GameState } from "../../game/store";
import { Progress, type GameAction } from "../common";

export function OperationsPage({ game, action }: { game: GameState; action: GameAction }) {
  const load = (game.customers / Math.max(1, game.employees * 72)) * 100;
  return <>
    <section className="content-grid operations-grid"><article className="panel branch-scene-card"><div className="branch-scene"><div className="mini-building large"><b>{game.bankName.slice(0, 1)}</b><i /><i /><i /><i /></div><div className="mini-tree left" /><div className="mini-tree right" /></div><div><p className="eyebrow">BRANCH NETWORK</p><h2>{game.branches} {game.branches === 1 ? "branch" : "branches"}</h2><p>Each branch adds local reach, capacity and a recurring operating cost.</p><button className="primary" disabled={game.cash < 2_400_000} onClick={() => action(openBranch)}>Open branch · NOK 2.4m</button></div></article><article className="panel"><p className="eyebrow">PEOPLE</p><h3>{game.employees} employees</h3><div className="people-number">{Math.round(game.customers / game.employees)}<small>customers per employee</small></div><Progress value={load} warning={load > 95} /><p className="muted">Recommended service load: below 72 customers per employee.</p><button className="secondary wide" disabled={game.cash < 95_000} onClick={() => action(hireEmployee)}>Hire employee · NOK 95k</button></article></section>
    <section className="content-grid two-column operations-lower"><article className="panel"><p className="eyebrow">DIGITAL BANK</p><div className="risk-heading"><span>Platform maturity</span><strong>{game.digitalLevel.toFixed(0)}/100</strong></div><Progress value={game.digitalLevel} /><button className="secondary wide" disabled={game.cash < 650_000 || game.digitalLevel >= 100} onClick={() => action(upgradeDigitalBank)}>Upgrade · NOK 650k</button></article><article className="panel"><p className="eyebrow">CYBER SECURITY</p><div className="risk-heading"><span>Control strength</span><strong>{game.cyberSecurity.toFixed(0)}/100</strong></div><Progress value={game.cyberSecurity} warning={game.cyberSecurity < 55} /><button className="secondary wide" disabled={game.cash < 420_000 || game.cyberSecurity >= 100} onClick={() => action(improveCyberSecurity)}>Strengthen controls · NOK 420k</button></article></section>
  </>;
}
