import { buildLoanReserve, investInCompliance, raiseEquityCapital, raiseWholesaleFunding, repayWholesaleFunding } from "../../game/engine";
import type { GameState } from "../../game/store";
import { Progress, type GameAction } from "../common";
import { money } from "../format";

export function RiskPage({ game, action }: { game: GameState; action: GameAction }) {
  return <>
    <section className="risk-layout"><div className="risk-score-card"><p className="eyebrow light">GROUP RISK SCORE</p><strong>{game.riskScore.toFixed(0)}</strong><small>Lower is better</small><div className="risk-ring" style={{ "--score": `${game.riskScore * 3.6}deg` }} /></div><div className="risk-cards"><article className="panel"><div className="risk-heading"><span>Capital ratio</span><strong>{game.capitalRatio.toFixed(1)}%</strong></div><Progress value={game.capitalRatio * 3.3} warning={game.capitalRatio < 12.5} /><small>{game.capitalBreachDays > 0 ? `${game.capitalBreachDays}/7 critical breach days` : "Internal target: 12.5%"}</small></article><article className="panel"><div className="risk-heading"><span>Liquidity</span><strong>{game.liquidityRatio.toFixed(1)}%</strong></div><Progress value={game.liquidityRatio * 1.8} warning={game.liquidityRatio < 18} /><small>Bank-run risk: {game.bankRunRisk.toFixed(0)}/100</small></article><article className="panel"><div className="risk-heading"><span>Compliance</span><strong>{game.compliance.toFixed(0)}/100</strong></div><Progress value={game.compliance} warning={game.compliance < 65} /><button className="secondary wide" disabled={game.cash < 320_000 || game.compliance >= 100} onClick={() => action(investInCompliance)}>Improve controls · NOK 320k</button></article></div></section>
    <section className="treasury-grid"><article className="panel treasury-card"><p className="eyebrow">WHOLESALE FUNDING</p><h3>{money.format(game.wholesaleFunding)}</h3><p>Current rate {game.wholesaleFundingRate.toFixed(2)}%. Market funding protects liquidity but increases daily interest expense.</p><div className="button-row"><button className="primary" onClick={() => action(raiseWholesaleFunding)}>Borrow NOK 5m</button><button className="secondary" disabled={game.wholesaleFunding <= 0 || game.cash < 6_000_000} onClick={() => action(repayWholesaleFunding)}>Repay NOK 5m</button></div></article><article className="panel treasury-card"><p className="eyebrow">LOSS ABSORBENCY</p><h3>{money.format(game.loanLossReserve)}</h3><p>NPL ratio {game.nplRatio.toFixed(2)}%. Increase reserves before an economic downturn or a wave of defaults.</p><button className="secondary" disabled={game.cash < 250_000} onClick={() => action(buildLoanReserve)}>Add NOK 250k reserve</button></article><article className="panel treasury-card"><p className="eyebrow">EQUITY CAPITAL</p><h3>{game.boardConfidence.toFixed(0)} board confidence</h3><p>Issue new shares to inject NOK 5 million. This dilutes the current owners.</p><button className="secondary" disabled={game.boardConfidence < 25} onClick={() => action(raiseEquityCapital)}>Raise equity</button></article></section>
  </>;
}
