import { useMemo, useState } from "react";
import {
  MANDATE_PERMISSION_LABELS,
  appointExecutiveV5,
  bestExecutiveRole,
  employeeDepartment,
  executiveRoleFit,
  getWorkforceDepartments,
  hireCandidateToRole,
  setExecutiveMandatePreset,
  toggleExecutivePermission,
  updateExecutiveMandateLimits,
} from "../../game/engine";
import type { ExecutiveRole, GameState, ManagementLogEntry, MandatePreset } from "../../game/store";
import type { EmployeeProfile } from "../../game/types";
import type { GameAction } from "../common";
import { money } from "../format";

const roles: ExecutiveRole[] = ["CFO", "COO", "CRO", "CMO", "CTO"];
const roleTitles: Record<ExecutiveRole, string> = { CFO: "Finance & Treasury", COO: "Operations & Branches", CRO: "Risk & Credit", CMO: "Customers & Growth", CTO: "Technology & Cyber" };

function managementSummary(items: ManagementLogEntry[]) {
  const credit = items.filter((item) => item.title.startsWith("Credit ·"));
  const other = items.filter((item) => !item.title.startsWith("Credit ·"));
  return [
    ...(credit.length ? [{ ...credit[0], id: `credit-summary-${credit[0].day}`, title: `${credit.length} credit decisions handled`, detail: "Routine approvals, counter-offers and declines were completed inside the CRO mandate." }] : []),
    ...other,
  ].sort((a, b) => b.day - a.day).slice(0, 6);
}

export function LeadershipPageV89({ game, action }: { game: GameState; action: GameAction }) {
  const departments = getWorkforceDepartments(game);
  const [selectedRole, setSelectedRole] = useState<ExecutiveRole>("CFO");
  const [selectedId, setSelectedId] = useState(game.employeeRoster[0]?.id ?? "");
  const [candidateId, setCandidateId] = useState(game.candidatePool[0]?.id ?? "");
  const selected = game.employeeRoster.find((employee) => employee.id === selectedId) ?? game.employeeRoster[0];
  const candidate = game.candidatePool.find((employee) => employee.id === candidateId) ?? game.candidatePool[0];
  const candidates = useMemo(() => [...game.candidatePool].sort((a, b) => bestExecutiveRole(b).fit - bestExecutiveRole(a).fit), [game.candidatePool]);
  const payroll = game.employeeRoster.reduce((sum, employee) => sum + employee.salary, 0);
  const performance = game.employeeRoster.reduce((sum, employee) => sum + (employee.performance ?? employee.skill), 0) / Math.max(1, game.employeeRoster.length);
  const wellbeing = game.employeeRoster.reduce((sum, employee) => sum + (employee.wellbeing ?? employee.energy), 0) / Math.max(1, game.employeeRoster.length);
  const overloaded = departments.filter((item) => item.status === "overloaded").length;
  const retention = game.employeeRoster.filter((employee) => employee.loyalty < 50 || (employee.quitRisk ?? 0) > 55 || (employee.wellbeing ?? employee.energy) < 45).length;
  const recentManagement = game.managementLog.filter((item) => item.day >= game.day - 30);
  const consolidatedActions = managementSummary(recentManagement.filter((item) => item.outcome !== "escalated")).length;
  const selectedExecutive = game.employeeRoster.find((employee) => employee.executiveRole === selectedRole);
  const selectedMandate = game.executiveMandates[selectedRole];
  const selectedRecent = managementSummary(recentManagement.filter((item) => item.role === selectedRole));
  const selectedCompleted = recentManagement.filter((item) => item.role === selectedRole && item.outcome !== "escalated").length;
  const selectedEscalated = recentManagement.filter((item) => item.role === selectedRole && item.outcome === "escalated").length;

  return <>
    <section className="v89-workforce-hero"><div><p className="eyebrow light">WORKFORCE & EXECUTIVE AUTHORITY</p><h2>One mandate system, one accountability trail</h2><p>Choose a role, set its authority once and review the decisions it actually made. Detailed controls now open in one full-width workspace instead of stretching a single card.</p></div><div><Headline label="Wellbeing" value={wellbeing.toFixed(0)} tone={wellbeing < 55 ? "warning" : "good"} /><Headline label="Employees" value={`${game.employeeRoster.length}`} /><Headline label="Payroll" value={money.format(payroll)} /><Headline label="Performance" value={performance.toFixed(0)} /></div></section>

    <section className="v89-workforce-kpis"><Headline label="Overloaded teams" value={`${overloaded}`} tone={overloaded ? "warning" : "good"} /><Headline label="Retention risk" value={`${retention}`} tone={retention ? "warning" : "good"} /><Headline label="Open CEO matters" value={`${game.ceoInbox.filter((item) => item.status === "open").length}`} /><Headline label="Decision groups · 30d" value={`${consolidatedActions}`} /></section>

    <section className="panel v89-mandate-section v810-mandate-section"><div className="panel-heading"><div><p className="eyebrow">EXECUTIVE MANDATES</p><h3>Pick a role, then configure it below</h3><p>The five cards remain comparable. Only the selected role opens a detailed authority and accountability workspace.</p></div><span className="status good">{roles.filter((role) => game.employeeRoster.some((employee) => employee.executiveRole === role)).length}/5 appointed</span></div>
      <div className="v810-mandate-picker">{roles.map((role) => { const executive = game.employeeRoster.find((employee) => employee.executiveRole === role); const mandate = game.executiveMandates[role]; const recent = recentManagement.filter((item) => item.role === role); const completed = recent.filter((item) => item.outcome !== "escalated").length; const escalated = recent.filter((item) => item.outcome === "escalated").length; return <button key={role} className={`${selectedRole === role ? "selected" : ""} ${executive ? "filled" : "vacant"}`} onClick={() => setSelectedRole(role)}><header><span>{role}</span><div><strong>{roleTitles[role]}</strong><small>{executive?.name ?? `Appoint a ${role}`}</small></div>{executive && <b>{executiveRoleFit(executive, role)}% fit</b>}</header><div><span><small>Preset</small><strong>{mandate.preset}</strong></span><span><small>Spend</small><strong>{money.format(mandate.spendLimit)}</strong></span><span><small>Risk</small><strong>{mandate.riskLimit.toFixed(0)}/100</strong></span><span><small>30 days</small><strong>{completed} handled · {escalated} escalated</strong></span></div></button>; })}</div>

      <article className="v810-mandate-workspace">
        <header><div><p className="eyebrow">{selectedRole} AUTHORITY</p><h3>{roleTitles[selectedRole]}</h3><p>{selectedExecutive ? `${selectedExecutive.name} owns this mandate with ${executiveRoleFit(selectedExecutive, selectedRole)}% role fit.` : `The role is vacant. Appoint a ${selectedRole} before authority can be used.`}</p></div><div className="v810-authority-summary"><span><small>Handled · 30d</small><strong>{selectedCompleted}</strong></span><span><small>Escalated · 30d</small><strong>{selectedEscalated}</strong></span><span><small>Spend ceiling</small><strong>{money.format(selectedMandate.spendLimit)}</strong></span><span><small>Risk ceiling</small><strong>{selectedMandate.riskLimit.toFixed(0)}</strong></span></div></header>
        {selectedExecutive ? <div className="v810-mandate-workspace-grid"><section className="v810-mandate-controls"><label><span>Operating preset</span><select value={selectedMandate.preset} onChange={(event) => { const preset = event.target.value as MandatePreset; if (preset !== "custom") action((state) => setExecutiveMandatePreset(state, selectedRole, preset)); }}><option value="cautious">Cautious · escalate often</option><option value="balanced">Balanced · normal authority</option><option value="autonomous">Autonomous · use the full mandate</option><option value="custom" disabled>Custom permissions</option></select></label><div className="v810-permission-list">{MANDATE_PERMISSION_LABELS[selectedRole].map((permission) => <label key={permission.key}><input type="checkbox" checked={selectedMandate.permissions.includes(permission.key)} onChange={() => action((state) => toggleExecutivePermission(state, selectedRole, permission.key))} /><span><strong>{permission.label}</strong><small>{selectedMandate.permissions.includes(permission.key) ? "Can execute inside the limits below" : "Must escalate or leave the work unresolved"}</small></span></label>)}</div><div className="v810-limit-controls"><label><span>Spending limit</span><input type="number" min="0" step="25000" value={selectedMandate.spendLimit} onChange={(event) => action((state) => updateExecutiveMandateLimits(state, selectedRole, { spendLimit: Number(event.target.value) }))} /><small>Any single action above this amount reaches the CEO.</small></label><label><span>Risk limit · {selectedMandate.riskLimit.toFixed(0)}/100</span><input type="range" min="0" max="100" value={selectedMandate.riskLimit} onChange={(event) => action((state) => updateExecutiveMandateLimits(state, selectedRole, { riskLimit: Number(event.target.value) }))} /><small>Higher values allow more aggressive decisions.</small></label></div></section><section className="v810-accountability-trail"><div><p className="eyebrow">ACCOUNTABILITY TRAIL</p><h3>What this executive actually did</h3><p>Routine credit work is grouped so the trail shows decisions rather than system noise.</p></div>{selectedRecent.length ? selectedRecent.map((item) => <article key={item.id}><span>{item.day}</span><div><strong>{item.title}</strong><small>{item.detail}</small></div><b>{item.outcome}{item.amount !== undefined ? ` · ${money.format(item.amount)}` : ""}</b></article>) : <div className="v89-compact-empty"><strong>No decisions in the last 30 days</strong><span>The executive will appear here after using the mandate or escalating a real exception.</span></div>}</section></div> : <div className="v89-compact-empty"><strong>{selectedRole} role is vacant</strong><span>Choose a suitable employee below or recruit from the talent market. Until then, this area cannot act automatically.</span></div>}
      </article>
    </section>

    <section className="panel v89-department-section"><div className="panel-heading"><div><p className="eyebrow">DEPARTMENT CAPACITY</p><h3>Workload before individual intervention</h3><p>Use this table to find the team creating the pressure, then inspect the people below.</p></div></div><div className="v89-department-table"><div><span>Department</span><span>Leader</span><span>Headcount</span><span>Workload</span><span>Performance</span><span>Wellbeing</span><span>Status</span></div>{departments.map((department) => <div key={department.department}><span><strong>{department.department}</strong><small>{department.leaderRole ? `${department.leaderRole} accountable` : "Executive team"}</small></span><span>{department.leader?.name ?? (department.leaderRole ? "Vacant" : game.founderName)}</span><span>{department.headcount}</span><span>{department.workload.toFixed(0)}%</span><span>{department.performance.toFixed(0)}</span><span>{department.wellbeing.toFixed(0)}</span><span><b className={`department-status ${department.status}`}>{department.status}</b></span></div>)}</div></section>

    <section className="v89-people-layout"><article className="panel"><div className="panel-heading"><div><p className="eyebrow">EMPLOYEE ROSTER</p><h3>Performance, workload and retention</h3></div></div><div className="v89-roster-list">{game.employeeRoster.map((employee) => <button key={employee.id} className={selected?.id === employee.id ? "selected" : ""} onClick={() => setSelectedId(employee.id)}><span>{employee.name.split(" ").map((part) => part[0]).join("")}</span><div><strong>{employee.name}</strong><small>{employee.executiveRole ? `${employee.executiveRole} · ` : ""}{employee.role}</small></div><b>{(employee.performance ?? employee.skill).toFixed(0)}</b><em>{(employee.workload ?? 75).toFixed(0)}% load</em></button>)}</div></article>{selected && <aside className="panel v89-person-card"><PersonHeader person={selected} label="EMPLOYEE" /><div className="v89-person-metrics"><Metric label="Performance" value={(selected.performance ?? selected.skill).toFixed(0)} /><Metric label="Workload" value={`${(selected.workload ?? 75).toFixed(0)}%`} /><Metric label="Wellbeing" value={(selected.wellbeing ?? selected.energy).toFixed(0)} /><Metric label="Loyalty" value={selected.loyalty.toFixed(0)} /><Metric label="Potential" value={(selected.potential ?? selected.skill).toFixed(0)} /><Metric label="Quit risk" value={`${(selected.quitRisk ?? 0).toFixed(0)}%`} /></div><Story person={selected} />{!selected.executiveRole && selected.leadership >= 55 && <div className="v89-role-actions">{roles.map((role) => <button key={role} disabled={executiveRoleFit(selected, role) < 58} onClick={() => action((state) => appointExecutiveV5(state, selected.id, role))}>Appoint {role} · {executiveRoleFit(selected, role)}%</button>)}</div>}</aside>}</section>

    <section className="panel v89-talent-section"><div className="panel-heading"><div><p className="eyebrow">TALENT MARKET</p><h3>Candidates with histories, ambitions and risk</h3></div><span className="status">{game.candidatePool.length} available</span></div><div className="v89-talent-layout"><div className="v89-candidate-list">{candidates.map((item) => { const best = bestExecutiveRole(item); return <button key={item.id} className={candidate?.id === item.id ? "selected" : ""} onClick={() => setCandidateId(item.id)}><span>{item.name.split(" ").map((part) => part[0]).join("")}</span><div><strong>{item.name}</strong><small>{item.role} · {item.nationality}</small><em>{item.leadershipStyle} · best fit {best.role} {best.fit}%</em></div><b>{money.format(item.salary)}/mo</b></button>; })}</div>{candidate && <aside className="v89-candidate-card"><PersonHeader person={candidate} label="CANDIDATE" /><div className="v89-person-metrics"><Metric label="Skill" value={`${candidate.skill}`} /><Metric label="Leadership" value={`${candidate.leadership}`} /><Metric label="Loyalty" value={`${candidate.loyalty}`} /><Metric label="Ambition" value={`${candidate.ambition ?? 50}`} /><Metric label="Board relation" value={`${candidate.boardRelationship ?? 50}`} /><Metric label="Available until" value={`Day ${candidate.availableUntilDay ?? "—"}`} /></div><Story person={candidate} /><div className="v89-role-actions">{roles.map((role) => <button key={role} disabled={game.cash < candidate.salary * 2 || executiveRoleFit(candidate, role) < 58} onClick={() => action((state) => hireCandidateToRole(state, candidate.id, role))}>Hire as {role} · {executiveRoleFit(candidate, role)}%</button>)}</div></aside>}</div></section>
  </>;
}

function Headline({ label, value, tone }: { label: string; value: string; tone?: string }) { return <span className={tone}><small>{label}</small><strong>{value}</strong></span>; }
function Metric({ label, value }: { label: string; value: string }) { return <span><small>{label}</small><strong>{value}</strong></span>; }
function PersonHeader({ person, label }: { person: EmployeeProfile; label: string }) { return <header><span>{person.name.split(" ").map((part) => part[0]).join("")}</span><div><p className="eyebrow">{label}</p><h3>{person.name}</h3><small>{employeeDepartment(person)} · {person.leadershipStyle ?? person.trait}</small></div></header>; }
function Story({ person }: { person: EmployeeProfile }) { return <div className="v89-person-story"><div><small>STRENGTHS</small>{(person.strengths ?? [person.trait]).map((item) => <span key={item}>+ {item}</span>)}</div><div><small>WEAKNESSES</small>{(person.weaknesses ?? []).map((item) => <span key={item}>− {item}</span>)}</div><div><small>STRATEGIC VIEW</small><strong>{person.strategyOpinion ?? "No stated position."}</strong></div></div>; }
