import { useMemo, useState } from "react";
import {
  MANDATE_PERMISSION_LABELS,
  appointExecutiveV5,
  bestExecutiveRole,
  employeeDepartment,
  executiveRoleFit,
  getWorkforceDepartments,
  hireCandidateToRole,
  setExecutiveMandatePreset,
  toggleExecutivePermission,
  updateExecutiveMandateLimits,
} from "../../game/engine";
import type { ExecutiveRole, GameState, MandatePreset } from "../../game/store";
import type { EmployeeProfile } from "../../game/types";
import type { GameAction } from "../common";
import { money } from "../format";

const roles: ExecutiveRole[] = ["CFO", "COO", "CRO", "CMO", "CTO"];
const roleTitles: Record<ExecutiveRole, string> = { CFO: "Finance & Treasury", COO: "Operations & Branches", CRO: "Risk & Credit", CMO: "Customers & Growth", CTO: "Technology & Cyber" };

export function LeadershipPageV89({ game, action }: { game: GameState; action: GameAction }) {
  const departments = getWorkforceDepartments(game);
  const [selectedId, setSelectedId] = useState(game.employeeRoster[0]?.id ?? "");
  const [candidateId, setCandidateId] = useState(game.candidatePool[0]?.id ?? "");
  const selected = game.employeeRoster.find((employee) => employee.id === selectedId) ?? game.employeeRoster[0];
  const candidate = game.candidatePool.find((employee) => employee.id === candidateId) ?? game.candidatePool[0];
  const candidates = useMemo(() => [...game.candidatePool].sort((a, b) => bestExecutiveRole(b).fit - bestExecutiveRole(a).fit), [game.candidatePool]);
  const payroll = game.employeeRoster.reduce((sum, employee) => sum + employee.salary, 0);
  const performance = game.employeeRoster.reduce((sum, employee) => sum + (employee.performance ?? employee.skill), 0) / Math.max(1, game.employeeRoster.length);
  const wellbeing = game.employeeRoster.reduce((sum, employee) => sum + (employee.wellbeing ?? employee.energy), 0) / Math.max(1, game.employeeRoster.length);
  const overloaded = departments.filter((item) => item.status === "overloaded").length;
  const retention = game.employeeRoster.filter((employee) => employee.loyalty < 50 || (employee.quitRisk ?? 0) > 55 || (employee.wellbeing ?? employee.energy) < 45).length;

  return <>
    <section className="v89-workforce-hero"><div><p className="eyebrow light">WORKFORCE & EXECUTIVE AUTHORITY</p><h2>One mandate system, one accountability trail</h2><p>Permissions, spending limits, risk limits and leader quality control real decisions across credit, treasury, branches, customers and technology.</p></div><div><Headline label="Wellbeing" value={wellbeing.toFixed(0)} tone={wellbeing < 55 ? "warning" : "good"} /><Headline label="Employees" value={`${game.employeeRoster.length}`} /><Headline label="Payroll" value={money.format(payroll)} /><Headline label="Performance" value={performance.toFixed(0)} /></div></section>

    <section className="v89-workforce-kpis"><Headline label="Overloaded teams" value={`${overloaded}`} tone={overloaded ? "warning" : "good"} /><Headline label="Retention risk" value={`${retention}`} tone={retention ? "warning" : "good"} /><Headline label="Open CEO matters" value={`${game.ceoInbox.filter((item) => item.status === "open").length}`} /><Headline label="Actions in 30d" value={`${game.managementLog.filter((item) => item.day >= game.day - 30 && item.outcome !== "escalated").length}`} /></section>

    <section className="panel v89-mandate-section"><div className="panel-heading"><div><p className="eyebrow">EXECUTIVE MANDATES</p><h3>Authority first, detailed permissions on demand</h3><p>The summary stays compact. Expand a role only when you need to change permissions or inspect recent decisions.</p></div><span className="status good">{roles.filter((role) => game.employeeRoster.some((employee) => employee.executiveRole === role)).length}/5 appointed</span></div>
      <div className="v89-mandate-grid">{roles.map((role) => { const executive = game.employeeRoster.find((employee) => employee.executiveRole === role); const mandate = game.executiveMandates[role]; const recent = game.managementLog.filter((item) => item.role === role && item.day >= game.day - 30); const completed = recent.filter((item) => item.outcome !== "escalated").length; const escalated = recent.filter((item) => item.outcome === "escalated").length; return <article key={role} className={executive ? "filled" : "vacant"}><header><span>{role}</span><div><strong>{roleTitles[role]}</strong><small>{executive?.name ?? `Appoint a ${role}`}</small></div>{executive && <b>{executiveRoleFit(executive, role)}% fit</b>}</header><div className="v89-mandate-summary"><span><small>Preset</small><strong>{mandate.preset}</strong></span><span><small>Spend limit</small><strong>{money.format(mandate.spendLimit)}</strong></span><span><small>Risk limit</small><strong>{mandate.riskLimit.toFixed(0)}/100</strong></span><span><small>30-day activity</small><strong>{completed} handled · {escalated} escalated</strong></span></div><details><summary>{executive ? "Configure mandate and view trail" : "Role inactive"}</summary>{executive && <div className="v89-mandate-details"><label><span>Preset</span><select value={mandate.preset} onChange={(event) => { const preset = event.target.value as MandatePreset; if (preset !== "custom") action((state) => setExecutiveMandatePreset(state, role, preset)); }}><option value="cautious">Cautious</option><option value="balanced">Balanced</option><option value="autonomous">Autonomous</option><option value="custom" disabled>Custom</option></select></label><div className="v89-permission-grid">{MANDATE_PERMISSION_LABELS[role].map((permission) => <label key={permission.key}><input type="checkbox" checked={mandate.permissions.includes(permission.key)} onChange={() => action((state) => toggleExecutivePermission(state, role, permission.key))} /><span>{permission.label}</span></label>)}</div><div className="v89-limit-grid"><label><span>Spending limit</span><input type="number" min="0" step="25000" value={mandate.spendLimit} onChange={(event) => action((state) => updateExecutiveMandateLimits(state, role, { spendLimit: Number(event.target.value) }))} /></label><label><span>Risk limit · {mandate.riskLimit.toFixed(0)}</span><input type="range" min="0" max="100" value={mandate.riskLimit} onChange={(event) => action((state) => updateExecutiveMandateLimits(state, role, { riskLimit: Number(event.target.value) }))} /></label></div><div className="v89-mandate-trail">{recent.slice(0, 4).map((item) => <div key={item.id}><strong>{item.title}</strong><small>{item.detail}</small><span>{item.outcome}{item.amount !== undefined ? ` · ${money.format(item.amount)}` : ""}</span></div>)}{recent.length === 0 && <p>No decisions recorded in the last 30 days.</p>}</div></div>}</details></article>; })}</div>
    </section>

    <section className="panel v89-department-section"><div className="panel-heading"><div><p className="eyebrow">DEPARTMENT CAPACITY</p><h3>Workload before individual intervention</h3></div></div><div className="v89-department-table"><div><span>Department</span><span>Leader</span><span>Headcount</span><span>Workload</span><span>Performance</span><span>Wellbeing</span><span>Status</span></div>{departments.map((department) => <div key={department.department}><span><strong>{department.department}</strong><small>{department.leaderRole ? `${department.leaderRole} accountable` : "Executive team"}</small></span><span>{department.leader?.name ?? (department.leaderRole ? "Vacant" : game.founderName)}</span><span>{department.headcount}</span><span>{department.workload.toFixed(0)}%</span><span>{department.performance.toFixed(0)}</span><span>{department.wellbeing.toFixed(0)}</span><span><b className={`department-status ${department.status}`}>{department.status}</b></span></div>)}</div></section>

    <section className="v89-people-layout"><article className="panel"><div className="panel-heading"><div><p className="eyebrow">EMPLOYEE ROSTER</p><h3>Performance, workload and retention</h3></div></div><div className="v89-roster-list">{game.employeeRoster.map((employee) => <button key={employee.id} className={selected?.id === employee.id ? "selected" : ""} onClick={() => setSelectedId(employee.id)}><span>{employee.name.split(" ").map((part) => part[0]).join("")}</span><div><strong>{employee.name}</strong><small>{employee.executiveRole ? `${employee.executiveRole} · ` : ""}{employee.role}</small></div><b>{(employee.performance ?? employee.skill).toFixed(0)}</b><em>{(employee.workload ?? 75).toFixed(0)}% load</em></button>)}</div></article>{selected && <aside className="panel v89-person-card"><PersonHeader person={selected} label="EMPLOYEE" /><div className="v89-person-metrics"><Metric label="Performance" value={(selected.performance ?? selected.skill).toFixed(0)} /><Metric label="Workload" value={`${(selected.workload ?? 75).toFixed(0)}%`} /><Metric label="Wellbeing" value={(selected.wellbeing ?? selected.energy).toFixed(0)} /><Metric label="Loyalty" value={selected.loyalty.toFixed(0)} /><Metric label="Potential" value={(selected.potential ?? selected.skill).toFixed(0)} /><Metric label="Quit risk" value={`${(selected.quitRisk ?? 0).toFixed(0)}%`} /></div><Story person={selected} />{!selected.executiveRole && selected.leadership >= 55 && <div className="v89-role-actions">{roles.map((role) => <button key={role} disabled={executiveRoleFit(selected, role) < 58} onClick={() => action((state) => appointExecutiveV5(state, selected.id, role))}>Appoint {role} · {executiveRoleFit(selected, role)}%</button>)}</div>}</aside>}</section>

    <section className="panel v89-talent-section"><div className="panel-heading"><div><p className="eyebrow">TALENT MARKET</p><h3>Candidates with histories, ambitions and risk</h3></div><span className="status">{game.candidatePool.length} available</span></div><div className="v89-talent-layout"><div className="v89-candidate-list">{candidates.map((item) => { const best = bestExecutiveRole(item); return <button key={item.id} className={candidate?.id === item.id ? "selected" : ""} onClick={() => setCandidateId(item.id)}><span>{item.name.split(" ").map((part) => part[0]).join("")}</span><div><strong>{item.name}</strong><small>{item.role} · {item.nationality}</small><em>{item.leadershipStyle} · best fit {best.role} {best.fit}%</em></div><b>{money.format(item.salary)}/mo</b></button>; })}</div>{candidate && <aside className="v89-candidate-card"><PersonHeader person={candidate} label="CANDIDATE" /><div className="v89-person-metrics"><Metric label="Skill" value={`${candidate.skill}`} /><Metric label="Leadership" value={`${candidate.leadership}`} /><Metric label="Loyalty" value={`${candidate.loyalty}`} /><Metric label="Ambition" value={`${candidate.ambition ?? 50}`} /><Metric label="Board relation" value={`${candidate.boardRelationship ?? 50}`} /><Metric label="Available until" value={`Day ${candidate.availableUntilDay ?? "—"}`} /></div><Story person={candidate} /><div className="v89-role-actions">{roles.map((role) => <button key={role} disabled={game.cash < candidate.salary * 2 || executiveRoleFit(candidate, role) < 58} onClick={() => action((state) => hireCandidateToRole(state, candidate.id, role))}>Hire as {role} · {executiveRoleFit(candidate, role)}%</button>)}</div></aside>}</div></section>
  </>;
}

function Headline({ label, value, tone }: { label: string; value: string; tone?: string }) { return <span className={tone}><small>{label}</small><strong>{value}</strong></span>; }
function Metric({ label, value }: { label: string; value: string }) { return <span><small>{label}</small><strong>{value}</strong></span>; }
function PersonHeader({ person, label }: { person: EmployeeProfile; label: string }) { return <header><span>{person.name.split(" ").map((part) => part[0]).join("")}</span><div><p className="eyebrow">{label}</p><h3>{person.name}</h3><small>{employeeDepartment(person)} · {person.leadershipStyle ?? person.trait}</small></div></header>; }
function Story({ person }: { person: EmployeeProfile }) { return <div className="v89-person-story"><div><small>STRENGTHS</small>{(person.strengths ?? [person.trait]).map((item) => <span key={item}>+ {item}</span>)}</div><div><small>WEAKNESSES</small>{(person.weaknesses ?? []).map((item) => <span key={item}>− {item}</span>)}</div><div><small>STRATEGIC VIEW</small><strong>{person.strategyOpinion ?? "No stated position."}</strong></div></div>; }
