import { approveLoanRefined, counterLoanRefined, declineLoanRefined, restructureLoan, updateProductTerms } from "../../game/engine";
import type { GameState, ProductKey } from "../../game/store";
import type { GameAction } from "../common";
import { money } from "../format";

const productNames: Record<ProductKey, string> = {
  everyday: "Everyday account", savings: "Savings", mortgage: "Mortgage", sme: "SME banking", cards: "Credit cards", insurance: "Insurance", wealth: "Wealth management",
};

export function ClientsPage({ game, action }: { game: GameState; action: GameAction }) {
  return <>
    <section className="segment-overview-grid">
      {game.customerSegments.map((segment) => <article className="segment-card panel" key={segment.key}><div className="segment-header"><span>{segment.name.slice(0, 1)}</span><div><strong>{segment.name}</strong><small>{segment.customers.toLocaleString("en-GB")} customers · {segment.preferredChannel}</small></div></div><div className="segment-kpis"><span><small>Satisfaction</small><b>{segment.satisfaction.toFixed(0)}</b></span><span><small>Loyalty</small><b>{segment.loyalty.toFixed(0)}</b></span><span><small>Profitability</small><b>{segment.profitability}</b></span><span className={segment.churnRisk > 24 ? "warn" : ""}><small>Churn risk</small><b>{segment.churnRisk.toFixed(0)}%</b></span></div></article>)}
    </section>

    <section className="panel product-lab"><div className="panel-heading"><div><p className="eyebrow">PRODUCT LAB</p><h3>Configure customer terms</h3></div><span className="status good">{game.products.length} live products</span></div>
      <div className="terms-grid">{(Object.keys(game.productTerms) as ProductKey[]).map((key) => { const terms = game.productTerms[key]; const active = game.products.includes(key); return <article className={active ? "terms-card active" : "terms-card locked"} key={key}><div className="terms-title"><strong>{productNames[key]}</strong><span>{active ? "Live" : "Locked"}</span></div><label>Customer rate <b>{terms.customerRate.toFixed(2)}%</b></label><input disabled={!active} type="range" min="0" max={key === "cards" ? 28 : 12} step="0.05" value={terms.customerRate} onChange={(event) => action((state) => updateProductTerms(state, key, { customerRate: Number(event.target.value) }))} /><label>Monthly fee <b>{money.format(terms.monthlyFee)}</b></label><input disabled={!active} type="range" min="0" max="1500" step="10" value={terms.monthlyFee} onChange={(event) => action((state) => updateProductTerms(state, key, { monthlyFee: Number(event.target.value) }))} /><label>Approval threshold <b>{terms.approvalThreshold}</b></label><input disabled={!active} type="range" min="25" max="95" step="1" value={terms.approvalThreshold} onChange={(event) => action((state) => updateProductTerms(state, key, { approvalThreshold: Number(event.target.value) }))} /><label>Service level <b>{terms.serviceLevel}</b></label><input disabled={!active} type="range" min="20" max="100" step="1" value={terms.serviceLevel} onChange={(event) => action((state) => updateProductTerms(state, key, { serviceLevel: Number(event.target.value) }))} /></article>; })}</div>
    </section>

    <section className="content-grid two-column credit-book-layout">
      <article className="panel"><div className="panel-heading"><div><p className="eyebrow">CREDIT COMMITTEE</p><h3>{game.loanApplications.length} pending cases</h3></div></div>
        {game.loanApplications.length === 0 ? <div className="empty-state">No large cases are waiting. New applications arrive as the bank grows.</div> : <div className="credit-case-list">{game.loanApplications.map((application) => <div className="credit-case refined" key={application.id}><div className="credit-case-head"><div><strong>{application.customerName}</strong><small>{application.segment}</small></div><span className={`risk-grade grade-${application.riskGrade.toLowerCase()}`}>{application.riskGrade}</span></div><div className="credit-facts"><span><small>Requested</small><b>{money.format(application.amount)}</b></span><span><small>Rate</small><b>{application.rate.toFixed(2)}%</b></span><span><small>Default probability</small><b>{application.defaultChance.toFixed(1)}%</b></span><span><small>Collateral</small><b>{application.collateral}%</b></span></div><div className="credit-actions"><button className="primary small" disabled={game.cash < application.amount} onClick={() => action((state) => approveLoanRefined(state, application.id))}>Approve</button><button className="secondary small" disabled={game.cash < application.amount * .72} onClick={() => action((state) => counterLoanRefined(state, application.id))}>Counter offer</button><button className="danger-button small" onClick={() => action((state) => declineLoanRefined(state, application.id))}>Decline</button></div></div>)}</div>}
      </article>
      <article className="panel"><div className="panel-heading"><div><p className="eyebrow">ACTIVE RELATIONSHIPS</p><h3>{game.activeLoans.length} tracked large loans</h3></div><span className={game.activeLoans.some((loan) => loan.status === "delinquent" || loan.status === "defaulted") ? "status warn" : "status good"}>{game.activeLoans.filter((loan) => loan.status !== "performing").length} watch cases</span></div>
        {game.activeLoans.length === 0 ? <div className="empty-state">Approved large cases will appear here with payment status and remaining exposure.</div> : <div className="loan-book">{game.activeLoans.map((loan) => <div className={`loan-row status-${loan.status}`} key={loan.id}><div><strong>{loan.customerName}</strong><small>{loan.segment} · originated day {loan.originatedDay}</small></div><span><small>Outstanding</small><b>{money.format(loan.outstanding)}</b></span><span><small>Rate</small><b>{loan.rate.toFixed(2)}%</b></span><span><small>Status</small><b>{loan.status}</b></span><button className="secondary small" disabled={loan.status !== "delinquent" && loan.status !== "watch"} onClick={() => action((state) => restructureLoan(state, loan.id))}>Restructure</button></div>)}</div>}
      </article>
    </section>
  </>;
}
