import { setMonthlyBudget } from "../../game/engine";
import type { GameState } from "../../game/store";
import { monthlyPayrollCost } from "../../game/utils";
import { ObjectiveCard, type GameAction } from "../common";
import { money } from "../format";

export function ReportsPage({ game, action }: { game: GameState; action: GameAction }) {
  const latest = game.reports[0];
  const support = game.boardMembers.reduce((sum, member) => sum + member.support * member.influence, 0) / Math.max(1, game.boardMembers.reduce((sum, member) => sum + member.influence, 0));
  const payroll = monthlyPayrollCost(game);
  const rent = game.branchOffices.reduce((sum, branch) => sum + branch.monthlyRent, 0);
  const technology = Math.round(game.digitalLevel * 24 * 30);
  const compliance = Math.round((480 + Math.max(0, 90 - game.compliance) * 18) * 30);
  const funding = Math.round(game.wholesaleFunding * game.wholesaleFundingRate / 100 / 12);
  const routineTotal = payroll + rent + technology + compliance + funding;

  return <>
    <section className="board-summary-card"><div><p className="eyebrow light">BOARD CONFIDENCE</p><h2>{support.toFixed(0)} / 100</h2><p>The board reacts to growth, risk, customers, technology and profit according to each member's priorities.</p></div><div className="board-vote-meter"><i style={{ width: `${support}%` }} /><span>{support >= 67 ? "Strong mandate" : support >= 45 ? "Fragile mandate" : "CEO under pressure"}</span></div></section>
    <section className="routine-cost-banner"><div><span>↻</span><div><strong>Routine operations run automatically</strong><p>Salaries, branch rent, ordinary technology, funding interest and baseline compliance are paid through the simulation. You do not approve these costs one by one.</p></div></div><b>{money.format(routineTotal)}<small>estimated monthly routine cost</small></b></section>
    <section className="routine-cost-grid"><CostCard label="Payroll" value={payroll} help="Monthly payroll for named employees and the remaining operating headcount." /><CostCard label="Branch rent" value={rent} help="Monthly rent across all operating locations." /><CostCard label="Technology" value={technology} help="Ordinary platform operation based on digital complexity." /><CostCard label="Compliance" value={compliance} help="Baseline monitoring and control work. Weak compliance makes this more expensive." /><CostCard label="Funding interest" value={funding} help="Interest paid on wholesale market funding." /></section>
    <section className="board-member-grid">{game.boardMembers.map((member) => <article className="panel board-member-card" key={member.id}><div className="board-person"><span>{member.name.split(" ").map((part) => part[0]).join("")}</span><div><strong>{member.name}</strong><small>{member.archetype}</small></div></div><div className="board-member-bottom"><span>Priority: <b>{member.priority}</b></span><strong className={member.support < 45 ? "negative" : ""}>{member.support.toFixed(0)} support</strong></div><div className="stage-track"><i style={{ width: `${member.support}%` }} /></div></article>)}</section>
    <section className="content-grid reports-top-grid">
      <article className="panel report-hero"><div className="panel-heading"><div><p className="eyebrow">LATEST MANAGEMENT REPORT</p><h3>{latest ? `Year ${latest.year} · Quarter ${latest.quarter} · Day ${latest.day}` : "First month not completed"}</h3></div>{latest && <span className={latest.netIncome >= 0 ? "status good" : "status warn"}>{latest.netIncome >= 0 ? "Profitable" : "Loss-making"}</span>}</div>{latest ? <><div className="report-kpi-grid"><ReportKpi label="Interest income" value={money.format(latest.interestIncome)} help="Interest earned from the loan portfolio." /><ReportKpi label="Fee income" value={money.format(latest.feeIncome)} help="Account, card, advisory and product fees." /><ReportKpi label="Operating expenses" value={money.format(latest.operatingExpenses)} help="Routine operating costs aggregated for the month." /><ReportKpi label="Credit losses" value={money.format(latest.creditLosses)} help="Losses from borrowers who did not repay as expected." /><ReportKpi label="Net income" value={money.format(latest.netIncome)} strong help="Income remaining after all costs and losses." /><ReportKpi label="Budget variance" value={money.format(latest.budgetVariance)} strong help="Positive means operating expenses finished below budget." /></div><div className="financial-equation"><span><small>Assets</small><b>{money.format(latest.assets)}</b></span><em>−</em><span><small>Liabilities</small><b>{money.format(latest.liabilities)}</b></span><em>=</em><span><small>Equity</small><b>{money.format(latest.equity)}</b></span></div></> : <div className="empty-state"><strong>No monthly report yet</strong><span>Advance to day 30. Normal costs are already running in the background while time moves.</span></div>}</article>
      <article className="panel budget-card"><p className="eyebrow">MONTHLY OPERATING BUDGET</p><h3>{money.format(game.monthlyBudget)}</h3><p>This is a management target, not a separate payment. A positive variance means ordinary operations finished below the target.</p><input type="range" min="250000" max="12000000" step="50000" value={game.monthlyBudget} onChange={(event) => action((state) => setMonthlyBudget(state, Number(event.target.value)))} /><div className="budget-range"><span>$250k</span><span>$12m</span></div>{latest && <div className={latest.budgetVariance >= 0 ? "budget-result positive" : "budget-result negative"}><small>Latest variance</small><strong>{money.format(latest.budgetVariance)}</strong></div>}</article>
    </section>
    <section className="panel"><div className="panel-heading"><div><p className="eyebrow">BOARD MANDATE</p><h3>Quarterly objectives</h3></div></div><div className="objectives-grid">{game.objectives.map((objective) => <ObjectiveCard key={objective.id} objective={objective} game={game} />)}</div></section>
    <section className="panel report-history"><div className="panel-heading"><div><p className="eyebrow">REPORT ARCHIVE</p><h3>{game.reports.length} monthly periods</h3></div></div>{game.reports.length === 0 ? <div className="empty-state">Completed reporting periods will be stored here.</div> : <div className="report-table"><div className="report-table-head"><span>Period</span><span>Revenue</span><span>Expenses</span><span>Credit losses</span><span>Net income</span><span>Equity</span></div>{game.reports.map((report) => <div className="report-table-row" key={report.id}><span>Y{report.year} Q{report.quarter} · D{report.day}</span><span>{money.format(report.interestIncome + report.feeIncome)}</span><span>{money.format(report.operatingExpenses)}</span><span>{money.format(report.creditLosses)}</span><strong className={report.netIncome < 0 ? "negative" : ""}>{money.format(report.netIncome)}</strong><span>{money.format(report.equity)}</span></div>)}</div>}</section>
  </>;
}

function CostCard({ label, value, help }: { label: string; value: number; help: string }) { return <article className="routine-cost-card" title={help}><small>{label}<i className="info-dot">i</i></small><strong>{money.format(value)}</strong><span>automatic each month</span></article>; }
function ReportKpi({ label, value, strong = false, help }: { label: string; value: string; strong?: boolean; help: string }) { return <span className={strong ? "report-kpi strong" : "report-kpi"} title={help}><small>{label}<i className="info-dot">i</i></small><b>{value}</b></span>; }
